import type { Metadata } from "next";
import { ResourceWorkspace } from "@/components/resource-workspace";
import { getOptions, getResource } from "@/lib/hr-data";
import type { ResourceConfig } from "@/types/resources";
export const metadata:Metadata={title:"Employee records"};
export default async function RecordsPage(){const [records,employees,types]=await Promise.all([getResource("documents"),getOptions("employees"),getOptions("document_types")]);const config:ResourceConfig={entity:"documents",title:"Employee records",description:"Securely manage contracts, certifications, IDs, and time-sensitive records.",singular:"Document",addLabel:"Add document",searchPlaceholder:"Search employee, document, number, or type…",columns:[
  {key:"title",label:"Document"},{key:"employee",label:"Employee",format:"person"},{key:"document_type",label:"Type"},{key:"document_number",label:"Document number"},{key:"expiration_date",label:"Expiration",format:"date"},{key:"verification_status",label:"Verification",format:"status"},{key:"confidentiality_level",label:"Access",format:"status"}],fields:[
  {name:"employee_id",label:"Employee",type:"select",required:true,options:employees,section:"Document details"},{name:"document_type_id",label:"Document type",type:"select",options:types,section:"Document details"},{name:"title",label:"Document title",type:"text",required:true,section:"Document details"},{name:"document_number",label:"Document number",type:"text",section:"Document details"},{name:"file",label:"Secure file",type:"file",colSpan:2,section:"Document details",helper:"PDF, JPG, or PNG up to 10 MB. Files are stored in a private bucket; replacing a file creates a new version."},{name:"issued_date",label:"Issued date",type:"date",section:"Validity"},{name:"expiration_date",label:"Expiration date",type:"date",section:"Validity",helper:"Used for expiration reminders and compliance reporting."},{name:"verification_status",label:"Verification status",type:"select",required:true,options:["pending","under_review","verified","rejected","expired"].map(x=>({label:x.replaceAll("_"," "),value:x})),section:"Control"},{name:"confidentiality_level",label:"Access level",type:"select",required:true,options:[{label:"Standard · Employee + HR",value:"standard"},{label:"Confidential · HR only",value:"confidential"},{label:"Highly confidential · Restricted HR",value:"highly_confidential"}],section:"Control"},{name:"status",label:"Record status",type:"select",required:true,options:["active","expired","archived"].map(x=>({label:x,value:x})),section:"Control"}
]};return <ResourceWorkspace config={config} records={records}/>;}
